# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cine', models.CharField(choices=[('cmxr', 'Cinemex Reforma'), ('cmxc', 'Cinemex Coapa')], max_length=50)),
                ('horario', models.CharField(choices=[('hc', '15:00'), ('hr', '20:00')], max_length=50)),
                ('imagen', models.ImageField(upload_to='', verbose_name='upload_to=')),
            ],
        ),
    ]
