# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
    ]
